DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS livros
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    abreviacao VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    autor VARCHAR(255),
    grupo VARCHAR(255),
    testamento VARCHAR(255)
);